use std::ffi::{OsStr, OsString};
use std::io::Write;
use std::path::Path;
#[cfg(test)]
use std::path::PathBuf;

use anyhow::{Context, Result, anyhow, bail};
use tempfile::Builder;

use super::{
    CommandOutput, CommandRunner, ServiceManager, ServiceManagerKind, ServiceSpec, ServiceStatus,
};

const TASK_NAME: &str = "Kwiry";
const TASK_MARKER: &str = "Managed by Kwiry (task schema 1)";
const SCHTASKS_EXE: &str = "schtasks.exe";
const RESTART_INTERVAL: &str = "PT1M";
const RESTART_COUNT: u8 = 3;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum TaskRegistration {
    Missing,
    Generated,
    Foreign,
}

pub(crate) struct WindowsTaskScheduler<R> {
    runner: R,
}

impl<R> WindowsTaskScheduler<R> {
    pub(crate) fn new(runner: R) -> Self {
        Self { runner }
    }
}

impl<R: CommandRunner> WindowsTaskScheduler<R> {
    fn run_schtasks(&self, operation: &str, args: &[OsString]) -> Result<CommandOutput> {
        self.runner
            .run(OsStr::new(SCHTASKS_EXE), args)
            .map_err(|_| anyhow!("could not execute {SCHTASKS_EXE} to {operation}"))
    }

    fn run_checked(&self, operation: &str, args: &[OsString]) -> Result<()> {
        let output = self.run_schtasks(operation, args)?;
        if output.code == Some(0) {
            Ok(())
        } else {
            Err(native_error(operation, &output))
        }
    }

    fn run_checked_allow_absent(&self, operation: &str, args: &[OsString]) -> Result<()> {
        let output = self.run_schtasks(operation, args)?;
        if output.code == Some(0) || is_missing_output(&output) || is_not_running_output(&output) {
            Ok(())
        } else {
            Err(native_error(operation, &output))
        }
    }

    fn inspect_registration(&self) -> Result<TaskRegistration> {
        let output =
            self.run_schtasks("inspect the scheduled task definition", &definition_args())?;
        if output.code == Some(0) {
            return Ok(if output.stdout.contains(TASK_MARKER) {
                TaskRegistration::Generated
            } else {
                TaskRegistration::Foreign
            });
        }
        if is_missing_output(&output) {
            return Ok(TaskRegistration::Missing);
        }
        Err(native_error(
            "inspect the scheduled task definition",
            &output,
        ))
    }

    fn query_status(&self) -> Result<ServiceStatus> {
        let output = self.run_schtasks("query the scheduled task", &query_args())?;
        if output.code == Some(0) {
            let (running, enabled) = parse_query_state(&output.stdout);
            let detail = if running {
                "Task Scheduler reports the task is running"
            } else if enabled {
                "Task Scheduler reports the task is stopped"
            } else {
                "Task Scheduler reports the task is disabled"
            };
            return Ok(ServiceStatus {
                manager: ServiceManagerKind::TaskScheduler,
                installed: true,
                enabled,
                running,
                detail: Some(detail.to_owned()),
            });
        }

        if is_missing_output(&output) {
            return Ok(ServiceStatus {
                manager: ServiceManagerKind::TaskScheduler,
                installed: false,
                enabled: false,
                running: false,
                detail: Some("Kwiry scheduled task is not registered".to_owned()),
            });
        }

        Err(native_error("query the scheduled task", &output))
    }
}

impl<R: CommandRunner> ServiceManager for WindowsTaskScheduler<R> {
    fn kind(&self) -> ServiceManagerKind {
        ServiceManagerKind::TaskScheduler
    }

    fn definition_matches(&self, spec: &ServiceSpec) -> Result<bool> {
        spec.validate()?;
        let output =
            self.run_schtasks("inspect the scheduled task definition", &definition_args())?;
        if is_missing_output(&output) {
            return Ok(false);
        }
        if output.code != Some(0) {
            return Err(native_error(
                "inspect the scheduled task definition",
                &output,
            ));
        }
        if !output.stdout.contains(TASK_MARKER) {
            bail!("refusing to inspect a scheduled task not generated by Kwiry: {TASK_NAME}");
        }
        let (executable, arguments) = task_action_fields(spec)?;
        Ok(output
            .stdout
            .contains(&format!("<Command>{}</Command>", xml_escape(executable)))
            && output.stdout.contains(&format!(
                "<Arguments>{}</Arguments>",
                xml_escape(&arguments)
            )))
    }

    fn install(&self, spec: &ServiceSpec) -> Result<()> {
        if self.inspect_registration()? == TaskRegistration::Foreign {
            bail!("refusing to replace a scheduled task not generated by Kwiry: {TASK_NAME}");
        }

        #[cfg(windows)]
        let sid = current_user_sid()?;
        #[cfg(not(windows))]
        let sid = non_windows_sid_error()?;

        let xml = render_task_xml(spec, &sid)?;
        with_temporary_task_xml(&xml, |path| {
            self.run_checked(
                "create or update the scheduled task",
                &create_or_update_args(path),
            )
        })
    }

    fn start(&self) -> Result<()> {
        match self.inspect_registration()? {
            TaskRegistration::Missing => bail!("Kwiry scheduled task is not installed"),
            TaskRegistration::Foreign => {
                bail!("refusing to start a scheduled task not generated by Kwiry: {TASK_NAME}")
            }
            TaskRegistration::Generated => {}
        }
        let status = self.query_status()?;
        if !status.installed {
            bail!("Kwiry scheduled task is not installed");
        }
        if status.running {
            return Ok(());
        }
        if !status.enabled {
            bail!("Kwiry scheduled task is disabled");
        }
        self.run_checked("start the scheduled task", &run_args())
    }

    fn stop(&self) -> Result<()> {
        match self.inspect_registration()? {
            TaskRegistration::Missing => return Ok(()),
            TaskRegistration::Foreign => {
                bail!("refusing to stop a scheduled task not generated by Kwiry: {TASK_NAME}")
            }
            TaskRegistration::Generated => {}
        }
        let status = self.query_status()?;
        if !status.installed || !status.running {
            return Ok(());
        }
        self.run_checked_allow_absent("stop the scheduled task", &end_args())
    }

    fn restart(&self) -> Result<()> {
        match self.inspect_registration()? {
            TaskRegistration::Missing => bail!("Kwiry scheduled task is not installed"),
            TaskRegistration::Foreign => {
                bail!("refusing to restart a scheduled task not generated by Kwiry: {TASK_NAME}")
            }
            TaskRegistration::Generated => {}
        }
        let status = self.query_status()?;
        if !status.installed {
            bail!("Kwiry scheduled task is not installed");
        }
        if !status.enabled {
            bail!("Kwiry scheduled task is disabled");
        }
        if status.running {
            self.run_checked_allow_absent("stop the scheduled task", &end_args())?;
        }
        self.run_checked("start the scheduled task", &run_args())
    }

    fn status(&self) -> Result<ServiceStatus> {
        self.query_status()
    }

    fn uninstall(&self) -> Result<()> {
        match self.inspect_registration()? {
            TaskRegistration::Missing => return Ok(()),
            TaskRegistration::Foreign => {
                bail!("refusing to remove a scheduled task not generated by Kwiry: {TASK_NAME}")
            }
            TaskRegistration::Generated => {}
        }
        let status = self.query_status()?;
        if !status.installed {
            return Ok(());
        }
        if status.running {
            self.run_checked_allow_absent("stop the scheduled task", &end_args())?;
        }
        self.run_checked_allow_absent("delete the scheduled task", &delete_args())
    }
}

fn task_action_fields(spec: &ServiceSpec) -> Result<(&str, String)> {
    let executable = absolute_path_text(&spec.executable, "executable")?;
    let config = absolute_path_text(&spec.config, "configuration file")?;
    let data_dir = absolute_path_text(&spec.data_dir, "data directory")?;
    let arguments = [
        "--config".to_owned(),
        quote_windows_argument(config),
        "--data-dir".to_owned(),
        quote_windows_argument(data_dir),
        "serve".to_owned(),
    ]
    .join(" ");
    Ok((executable, arguments))
}

pub(crate) fn render_task_xml(spec: &ServiceSpec, sid: &str) -> Result<String> {
    let (executable, arguments) = task_action_fields(spec)?;
    if sid.trim().is_empty() {
        bail!("current-user SID is empty");
    }

    Ok(format!(
        r#"<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>{TASK_MARKER}</Description>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <UserId>{sid}</UserId>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>{sid}</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
    <RestartOnFailure>
      <Interval>{RESTART_INTERVAL}</Interval>
      <Count>{RESTART_COUNT}</Count>
    </RestartOnFailure>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>{executable}</Command>
      <Arguments>{arguments}</Arguments>
    </Exec>
  </Actions>
</Task>
"#,
        sid = xml_escape(sid),
        executable = xml_escape(executable),
        arguments = xml_escape(&arguments),
    ))
}

fn absolute_path_text<'a>(path: &'a Path, label: &str) -> Result<&'a str> {
    let text = path
        .to_str()
        .ok_or_else(|| anyhow!("Kwiry service {label} path is not valid Unicode"))?;
    if !path.is_absolute() && !is_windows_absolute(text) {
        bail!("Kwiry service {label} path must be absolute");
    }
    Ok(text)
}

fn is_windows_absolute(path: &str) -> bool {
    let bytes = path.as_bytes();
    (bytes.len() >= 3
        && bytes[0].is_ascii_alphabetic()
        && bytes[1] == b':'
        && matches!(bytes[2], b'\\' | b'/'))
        || path.starts_with(r"\\")
        || path.starts_with("//")
}

fn xml_escape(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for character in value.chars() {
        match character {
            '&' => escaped.push_str("&amp;"),
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '"' => escaped.push_str("&quot;"),
            '\'' => escaped.push_str("&apos;"),
            _ => escaped.push(character),
        }
    }
    escaped
}

fn quote_windows_argument(value: &str) -> String {
    let mut quoted = String::with_capacity(value.len() + 2);
    quoted.push('"');
    let mut backslashes = 0;

    for character in value.chars() {
        if character == '\\' {
            backslashes += 1;
            continue;
        }

        if character == '"' {
            quoted.extend(std::iter::repeat_n('\\', backslashes * 2 + 1));
            quoted.push('"');
        } else {
            quoted.extend(std::iter::repeat_n('\\', backslashes));
            quoted.push(character);
        }
        backslashes = 0;
    }

    quoted.extend(std::iter::repeat_n('\\', backslashes * 2));
    quoted.push('"');
    quoted
}

fn with_temporary_task_xml<T>(xml: &str, action: impl FnOnce(&Path) -> Result<T>) -> Result<T> {
    let mut temporary = Builder::new()
        .prefix("kwiry-task-")
        .suffix(".xml")
        .tempfile()
        .context("could not create temporary Task Scheduler XML")?;
    write_utf16le(&mut temporary, xml).context("could not write temporary Task Scheduler XML")?;
    temporary
        .flush()
        .context("could not flush temporary Task Scheduler XML")?;
    action(temporary.path())
}

fn write_utf16le(writer: &mut impl Write, text: &str) -> std::io::Result<()> {
    writer.write_all(&[0xff, 0xfe])?;
    for unit in text.encode_utf16() {
        writer.write_all(&unit.to_le_bytes())?;
    }
    Ok(())
}

fn create_or_update_args(xml_path: &Path) -> Vec<OsString> {
    vec![
        "/Create".into(),
        "/TN".into(),
        TASK_NAME.into(),
        "/XML".into(),
        xml_path.as_os_str().to_owned(),
        "/F".into(),
    ]
}

fn run_args() -> Vec<OsString> {
    task_args("/Run")
}

fn end_args() -> Vec<OsString> {
    task_args("/End")
}

fn definition_args() -> Vec<OsString> {
    vec![
        "/Query".into(),
        "/TN".into(),
        TASK_NAME.into(),
        "/XML".into(),
    ]
}

fn query_args() -> Vec<OsString> {
    vec![
        "/Query".into(),
        "/TN".into(),
        TASK_NAME.into(),
        "/FO".into(),
        "LIST".into(),
        "/V".into(),
    ]
}

fn delete_args() -> Vec<OsString> {
    vec![
        "/Delete".into(),
        "/TN".into(),
        TASK_NAME.into(),
        "/F".into(),
    ]
}

fn task_args(operation: &str) -> Vec<OsString> {
    vec![operation.into(), "/TN".into(), TASK_NAME.into()]
}

fn parse_query_state(stdout: &str) -> (bool, bool) {
    let mut running = false;
    let mut enabled = true;
    for line in stdout.lines() {
        let Some((label, value)) = line.split_once(':') else {
            continue;
        };
        let label = label.trim();
        let value = value.trim();
        if label.eq_ignore_ascii_case("status") {
            running = value.eq_ignore_ascii_case("running");
        } else if label.eq_ignore_ascii_case("scheduled task state") {
            enabled = !value.eq_ignore_ascii_case("disabled");
        }
    }
    (running, enabled)
}

fn native_error(operation: &str, output: &CommandOutput) -> anyhow::Error {
    let detail = sanitized_native_detail(output);
    let code = output.code.map_or_else(
        || "terminated without an exit code".to_owned(),
        |code| format!("exit code {code}"),
    );
    anyhow!("Task Scheduler could not {operation}: {SCHTASKS_EXE} failed with {code}: {detail}")
}

fn sanitized_native_detail(output: &CommandOutput) -> String {
    let raw = if output.stderr.trim().is_empty() {
        output.stdout.as_str()
    } else {
        output.stderr.as_str()
    };
    let single_line = raw
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace(|character: char| character.is_control(), "");
    if single_line.is_empty() {
        return "no diagnostic was provided".to_owned();
    }

    const MAX_CHARS: usize = 240;
    let mut characters = single_line.chars();
    let mut sanitized: String = characters.by_ref().take(MAX_CHARS).collect();
    if characters.next().is_some() {
        sanitized.push('…');
    }
    sanitized
}

fn is_missing_output(output: &CommandOutput) -> bool {
    let detail = format!("{}\n{}", output.stdout, output.stderr).to_ascii_lowercase();
    [
        "0x80070002",
        "cannot find the file specified",
        "cannot find the task",
        "task does not exist",
        "does not exist in the system",
        "task was not found",
    ]
    .iter()
    .any(|marker| detail.contains(marker))
}

fn is_not_running_output(output: &CommandOutput) -> bool {
    let detail = format!("{}\n{}", output.stdout, output.stderr).to_ascii_lowercase();
    detail.contains("not currently running") || detail.contains("is not running")
}

#[cfg(not(windows))]
fn non_windows_sid_error() -> Result<String> {
    bail!("Windows Task Scheduler service installation is only available on Windows")
}

#[cfg(windows)]
fn current_user_sid() -> Result<String> {
    use std::ptr;

    use windows_sys::Win32::Foundation::{CloseHandle, HANDLE, LocalFree};
    use windows_sys::Win32::Security::Authorization::ConvertSidToStringSidW;
    use windows_sys::Win32::Security::{GetTokenInformation, TOKEN_QUERY, TOKEN_USER, TokenUser};
    use windows_sys::Win32::System::Threading::{GetCurrentProcess, OpenProcessToken};

    let mut token: HANDLE = ptr::null_mut();
    // SAFETY: `token` is a valid out-pointer and the pseudo-handle is owned by Windows.
    let opened = unsafe { OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &mut token) };
    if opened == 0 {
        return Err(std::io::Error::last_os_error())
            .context("could not open the current process token");
    }

    let result = (|| {
        let mut required = 0_u32;
        // SAFETY: This call intentionally queries the required buffer size.
        unsafe {
            GetTokenInformation(token, TokenUser, ptr::null_mut(), 0, &mut required);
        }
        if required == 0 {
            return Err(std::io::Error::last_os_error())
                .context("could not size the current-user token information");
        }

        let mut buffer = vec![0_u8; required as usize];
        // SAFETY: `buffer` has the size reported by `GetTokenInformation`.
        let loaded = unsafe {
            GetTokenInformation(
                token,
                TokenUser,
                buffer.as_mut_ptr().cast(),
                required,
                &mut required,
            )
        };
        if loaded == 0 {
            return Err(std::io::Error::last_os_error())
                .context("could not read the current-user token information");
        }

        // SAFETY: `GetTokenInformation(TokenUser)` initialized a TOKEN_USER at the buffer start;
        // unaligned read avoids relying on Vec<u8> alignment, and its SID pointer remains valid.
        let token_user = unsafe { buffer.as_ptr().cast::<TOKEN_USER>().read_unaligned() };
        let mut sid_text = ptr::null_mut();
        // SAFETY: The SID pointer belongs to the live token information buffer, and the API writes
        // a LocalAlloc-owned, NUL-terminated UTF-16 string to `sid_text`.
        let converted = unsafe { ConvertSidToStringSidW(token_user.User.Sid, &mut sid_text) };
        if converted == 0 {
            return Err(std::io::Error::last_os_error())
                .context("could not convert the current-user SID to text");
        }

        let mut length = 0;
        // SAFETY: A successful conversion returns a valid NUL-terminated UTF-16 allocation.
        unsafe {
            while *sid_text.add(length) != 0 {
                length += 1;
            }
        }
        // SAFETY: `sid_text` is valid for `length` initialized UTF-16 code units.
        let sid = unsafe { String::from_utf16_lossy(std::slice::from_raw_parts(sid_text, length)) };
        // SAFETY: `sid_text` was allocated by ConvertSidToStringSidW.
        unsafe {
            LocalFree(sid_text.cast());
        }
        Ok(sid)
    })();

    // SAFETY: `token` is a real handle returned by OpenProcessToken.
    unsafe {
        CloseHandle(token);
    }
    result
}

#[cfg(test)]
mod tests {
    use std::collections::VecDeque;
    use std::fs;
    use std::sync::Mutex;

    use tempfile::tempdir;

    use super::*;

    fn spec(executable: PathBuf, config: PathBuf, data_dir: PathBuf) -> ServiceSpec {
        ServiceSpec {
            executable,
            config,
            data_dir,
        }
    }

    fn sample_spec() -> ServiceSpec {
        spec(
            PathBuf::from(r"C:\Program Files\Kwiry & Tools\kwiry.exe"),
            PathBuf::from(r#"C:\Users\Zoë\Kwiry "config" & notes\config.toml"#),
            PathBuf::from(r"C:\Users\Zoë\data <primary> & > archive"),
        )
    }

    #[test]
    fn task_xml_has_exact_current_user_security_and_resilient_settings() {
        let xml = render_task_xml(&sample_spec(), "S-1-5-21-1000").unwrap();

        assert!(xml.contains(&format!("<Description>{TASK_MARKER}</Description>")));
        assert_eq!(xml.matches("<UserId>S-1-5-21-1000</UserId>").count(), 2);
        assert!(xml.contains("<LogonType>InteractiveToken</LogonType>"));
        assert!(xml.contains("<RunLevel>LeastPrivilege</RunLevel>"));
        assert!(xml.contains("<MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>"));
        assert!(xml.contains("<StartWhenAvailable>true</StartWhenAvailable>"));
        assert!(xml.contains("<ExecutionTimeLimit>PT0S</ExecutionTimeLimit>"));
        assert!(xml.contains("<DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>"));
        assert!(xml.contains("<StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>"));
        assert!(xml.contains(
            "<RestartOnFailure>\n      <Interval>PT1M</Interval>\n      <Count>3</Count>"
        ));
        assert!(!xml.contains("<Password>"));
        assert!(!xml.contains("<GroupId>"));
    }

    #[test]
    fn task_definition_matching_detects_executable_drift() {
        #[cfg(windows)]
        let expected = sample_spec();
        #[cfg(not(windows))]
        let expected = spec(
            PathBuf::from("/opt/kwiry.exe"),
            PathBuf::from("/config/config.toml"),
            PathBuf::from("/data/index"),
        );
        let xml = render_task_xml(&expected, "S-1-5-21-1000").unwrap();
        let matching = WindowsTaskScheduler::new(FakeRunner::new([output(0, &xml, "")]));
        assert!(matching.definition_matches(&expected).unwrap());

        let mut moved = expected.clone();
        #[cfg(windows)]
        {
            moved.executable = PathBuf::from(r"C:\Program Files\Kwiry\kwiry.exe");
        }
        #[cfg(not(windows))]
        {
            moved.executable = PathBuf::from("/opt/new/kwiry.exe");
        }
        let drifted = WindowsTaskScheduler::new(FakeRunner::new([output(0, &xml, "")]));
        assert!(!drifted.definition_matches(&moved).unwrap());
    }

    #[test]
    fn task_xml_escapes_paths_quotes_markup_ampersands_and_unicode() {
        let xml = render_task_xml(&sample_spec(), "S-1-5-21-1000").unwrap();

        assert!(xml.contains(r"<Command>C:\Program Files\Kwiry &amp; Tools\kwiry.exe</Command>"));
        assert!(xml.contains(
            r#"--config &quot;C:\Users\Zoë\Kwiry \&quot;config\&quot; &amp; notes\config.toml&quot;"#
        ));
        assert!(xml.contains(
            r"--data-dir &quot;C:\Users\Zoë\data &lt;primary&gt; &amp; &gt; archive&quot; serve"
        ));
        assert!(!xml.contains("Kwiry & Tools"));
        assert!(!xml.contains("data <primary>"));
    }

    #[test]
    fn task_xml_rejects_relative_service_paths() {
        let error = render_task_xml(
            &spec(
                PathBuf::from("kwiry.exe"),
                PathBuf::from("/config.toml"),
                PathBuf::from("/data"),
            ),
            "S-1-5-21-1000",
        )
        .unwrap_err();

        assert!(
            error
                .to_string()
                .contains("executable path must be absolute")
        );
    }

    #[test]
    fn schtasks_arguments_are_direct_and_have_no_shell_layer() {
        let xml_path = Path::new("/tmp/Kwiry task.xml");
        assert_eq!(
            create_or_update_args(xml_path),
            vec![
                OsString::from("/Create"),
                OsString::from("/TN"),
                OsString::from("Kwiry"),
                OsString::from("/XML"),
                xml_path.as_os_str().to_owned(),
                OsString::from("/F"),
            ]
        );
        assert_eq!(run_args(), os_strings(&["/Run", "/TN", "Kwiry"]));
        assert_eq!(end_args(), os_strings(&["/End", "/TN", "Kwiry"]));
        assert_eq!(
            definition_args(),
            os_strings(&["/Query", "/TN", "Kwiry", "/XML"])
        );
        assert_eq!(
            query_args(),
            os_strings(&["/Query", "/TN", "Kwiry", "/FO", "LIST", "/V"])
        );
        assert_eq!(
            delete_args(),
            os_strings(&["/Delete", "/TN", "Kwiry", "/F"])
        );
        for forbidden in ["cmd.exe", "powershell.exe", ".bat", "/C"] {
            assert!(
                !create_or_update_args(xml_path)
                    .iter()
                    .any(|arg| arg == forbidden)
            );
        }
    }

    #[test]
    fn temporary_xml_is_utf16_and_removed_after_success_or_error() {
        let xml = render_task_xml(&sample_spec(), "S-1-5-21-1000").unwrap();
        let observed = Mutex::new(Vec::<PathBuf>::new());

        with_temporary_task_xml(&xml, |path| {
            observed.lock().unwrap().push(path.to_owned());
            let bytes = fs::read(path).unwrap();
            assert_eq!(&bytes[..2], &[0xff, 0xfe]);
            assert!(path.exists());
            Ok(())
        })
        .unwrap();
        let first = observed.lock().unwrap()[0].clone();
        assert!(!first.exists());

        let failed: Result<()> = with_temporary_task_xml(&xml, |path| {
            observed.lock().unwrap().push(path.to_owned());
            bail!("simulated schtasks failure")
        });
        assert!(failed.is_err());
        let second = observed.lock().unwrap()[1].clone();
        assert!(!second.exists());
    }

    #[test]
    fn rendered_definition_and_commands_never_contain_secret_sentinel() {
        const SECRET: &str = "KWIRY_SECRET_SENTINEL_7fa962";
        let xml = render_task_xml(&sample_spec(), "S-1-5-21-1000").unwrap();
        assert!(!xml.contains(SECRET));
        for args in [
            run_args(),
            end_args(),
            definition_args(),
            query_args(),
            delete_args(),
        ] {
            assert!(
                !args
                    .iter()
                    .any(|arg| arg.to_string_lossy().contains(SECRET))
            );
        }
    }

    #[test]
    fn uninstall_uses_only_task_scheduler_and_never_deletes_data() {
        let temporary = tempdir().unwrap();
        let config = temporary.path().join("config.toml");
        let data = temporary.path().join("data");
        fs::write(&config, "sentinel config").unwrap();
        fs::create_dir(&data).unwrap();
        fs::write(data.join("sentinel"), "keep me").unwrap();

        let runner = FakeRunner::new([
            output(0, &format!("<Description>{TASK_MARKER}</Description>"), ""),
            output(0, "Status: Running", ""),
            output(0, "SUCCESS", ""),
            output(0, "SUCCESS", ""),
        ]);
        let manager = WindowsTaskScheduler::new(runner);
        manager.uninstall().unwrap();

        assert_eq!(fs::read_to_string(config).unwrap(), "sentinel config");
        assert_eq!(
            fs::read_to_string(data.join("sentinel")).unwrap(),
            "keep me"
        );
        let calls = manager.runner.calls.lock().unwrap();
        assert_eq!(calls.len(), 4);
        assert_eq!(calls[0].1, definition_args());
        assert_eq!(calls[1].1, query_args());
        assert_eq!(calls[2].1, end_args());
        assert_eq!(calls[3].1, delete_args());
    }

    #[test]
    fn uninstall_refuses_a_foreign_task_with_the_same_name() {
        let manager = WindowsTaskScheduler::new(FakeRunner::new([output(
            0,
            "<Description>Someone else's task</Description>",
            "",
        )]));

        let error = manager.uninstall().unwrap_err();

        assert!(error.to_string().contains("not generated by Kwiry"));
        let calls = manager.runner.calls.lock().unwrap();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].1, definition_args());
    }

    #[test]
    fn lifecycle_is_idempotent_for_missing_running_and_stopped_tasks() {
        let missing = WindowsTaskScheduler::new(FakeRunner::new([output(
            1,
            "",
            "ERROR: The system cannot find the file specified.",
        )]));
        missing.stop().unwrap();
        assert_eq!(missing.runner.calls.lock().unwrap().len(), 1);

        let generated = format!("<Description>{TASK_MARKER}</Description>");
        let running = WindowsTaskScheduler::new(FakeRunner::new([
            output(0, &generated, ""),
            output(0, "Status: Running", ""),
        ]));
        running.start().unwrap();
        assert_eq!(running.runner.calls.lock().unwrap().len(), 2);

        let stopped = WindowsTaskScheduler::new(FakeRunner::new([
            output(0, &generated, ""),
            output(0, "Status: Ready", ""),
        ]));
        stopped.stop().unwrap();
        assert_eq!(stopped.runner.calls.lock().unwrap().len(), 2);
    }

    #[test]
    fn query_state_uses_status_fields_not_unrelated_running_text() {
        assert_eq!(
            parse_query_state(
                "Task To Run: C:\\Tools\\running\r\nStatus: Ready\r\nScheduled Task State: Enabled"
            ),
            (false, true)
        );
        assert_eq!(
            parse_query_state("Status: Running\r\nScheduled Task State: Enabled"),
            (true, true)
        );
        assert_eq!(
            parse_query_state("Status: Ready\r\nScheduled Task State: Disabled"),
            (false, false)
        );
    }

    #[test]
    fn native_errors_are_single_line_bounded_and_do_not_include_command_arguments() {
        let output = CommandOutput {
            code: Some(5),
            stdout: String::new(),
            stderr: format!("access denied\r\n{}", "x".repeat(400)),
        };
        let message = native_error("create the scheduled task", &output).to_string();

        assert!(!message.contains('\n'));
        assert!(!message.contains("/XML"));
        assert!(message.contains("exit code 5"));
        assert!(message.ends_with('…'));
        assert!(message.chars().count() < 340);
    }

    fn os_strings(values: &[&str]) -> Vec<OsString> {
        values.iter().map(OsString::from).collect()
    }

    fn output(code: i32, stdout: &str, stderr: &str) -> CommandOutput {
        CommandOutput {
            code: Some(code),
            stdout: stdout.to_owned(),
            stderr: stderr.to_owned(),
        }
    }

    struct FakeRunner {
        outputs: Mutex<VecDeque<CommandOutput>>,
        calls: Mutex<Vec<(PathBuf, Vec<OsString>)>>,
    }

    impl FakeRunner {
        fn new(outputs: impl IntoIterator<Item = CommandOutput>) -> Self {
            Self {
                outputs: Mutex::new(outputs.into_iter().collect()),
                calls: Mutex::new(Vec::new()),
            }
        }
    }

    impl CommandRunner for FakeRunner {
        fn run(&self, program: &OsStr, args: &[OsString]) -> Result<CommandOutput> {
            self.calls
                .lock()
                .unwrap()
                .push((PathBuf::from(program), args.to_vec()));
            self.outputs
                .lock()
                .unwrap()
                .pop_front()
                .ok_or_else(|| anyhow!("unexpected command"))
        }
    }
}
